#ifndef _MATHH_PREFIX
#define _MATHH_PREFIX

#ifdef __AVR__

#include_next <math.h>

// List generated by running this on the errors when trying to build:
// grep "has not been declared" errors | sed -r "s/.*::([^']+)[lf].*/\1/" | uniq > calls
// cat calls | sed -r 's/(.*)/#define \1l \1/'

#define _AVR_GENERATE_OVERLOADS(MATHFUNC)                                      \
    static inline float MATHFUNC##f(float val) {                               \
        return ::MATHFUNC((double)val);                                        \
    }                                                                          \
    static inline long double MATHFUNC##l(long double val) {                   \
        return ::MATHFUNC((double)val);                                        \
    }
#if 1
#define acosl acos
#define asinl asin
#define atanl atan
#define atan2l atan2
#define ceill ceil
#define cosl cos
#define coshl cosh
#define expl exp
#define fabsl fabs
#define floorl floor
#define fmodl fmod
#define frexpl frexp
#define ldexpl ldexp
#define logl log
#define log10l log10
#define modfl modf
#define powl pow
#define sinl sin
#define sinhl sinh
#define sqrtl sqrt
#define tanl tan
#define tanhl tanh
#define acoshl acosh
#define asinhl asinh
#define atanhl atanh
#define cbrtl cbrt
#define copysignl copysign
#define erfl erf
#define erfcl erfc
#define exp2l exp2
#define expm1l expm1
#define fdiml fdim
#define fmal fma
#define fmaxl fmax
#define fminl fmin
#define hypotl hypot
#define ilogbl ilogb
#define lgammal lgamma
#define llrintl llrint
#define llroundl llround
#define log1pl log1p
#define log2l log2
#define logbl logb
#define lrintl lrint
#define lroundl lround
#define nearbyintl nearbyint
#define nextafterl nextafter
#define nexttowardl nexttoward
#define remainderl remainder
#define remquol remquo
#define roundl round
#define truncl trunc
#else
#undef acosf
_AVR_GENERATE_OVERLOADS(acos)
#undef asinf
_AVR_GENERATE_OVERLOADS(asin)
#undef atanf
_AVR_GENERATE_OVERLOADS(atan)
#undef atan2f
_AVR_GENERATE_OVERLOADS(atan2)
#undef ceilf
_AVR_GENERATE_OVERLOADS(ceil)
#undef cosf
_AVR_GENERATE_OVERLOADS(cos)
#undef coshf
_AVR_GENERATE_OVERLOADS(cosh)
#undef expf
_AVR_GENERATE_OVERLOADS(exp)
#undef fabsf
_AVR_GENERATE_OVERLOADS(fabs)
#undef floorf
_AVR_GENERATE_OVERLOADS(floor)
#undef fmodf
_AVR_GENERATE_OVERLOADS(fmod)
#undef frexpf
_AVR_GENERATE_OVERLOADS(frexp)
#undef ldexpf
_AVR_GENERATE_OVERLOADS(ldexp)
#undef logf
_AVR_GENERATE_OVERLOADS(log)
#undef log10f
_AVR_GENERATE_OVERLOADS(log10)
#undef modff
_AVR_GENERATE_OVERLOADS(modf)
#undef powf
_AVR_GENERATE_OVERLOADS(pow)
#undef sinf
_AVR_GENERATE_OVERLOADS(sin)
#undef sinhf
_AVR_GENERATE_OVERLOADS(sinh)
#undef sqrtf
_AVR_GENERATE_OVERLOADS(sqrt)
#undef tanf
_AVR_GENERATE_OVERLOADS(tan)
#undef tanhf
_AVR_GENERATE_OVERLOADS(tanh)
#undef acoshf
_AVR_GENERATE_OVERLOADS(acosh)
#undef asinhf
_AVR_GENERATE_OVERLOADS(asinh)
#undef atanhf
_AVR_GENERATE_OVERLOADS(atanh)
#undef cbrtf
_AVR_GENERATE_OVERLOADS(cbrt)
#undef copysignf
_AVR_GENERATE_OVERLOADS(copysign)
#undef erff
_AVR_GENERATE_OVERLOADS(erf)
#undef erfcf
_AVR_GENERATE_OVERLOADS(erfc)
#undef exp2f
_AVR_GENERATE_OVERLOADS(exp2)
#undef expm1f
_AVR_GENERATE_OVERLOADS(expm1)
#undef fdimf
_AVR_GENERATE_OVERLOADS(fdim)
#undef fmaf
_AVR_GENERATE_OVERLOADS(fma)
#undef fmaxf
_AVR_GENERATE_OVERLOADS(fmax)
#undef fminf
_AVR_GENERATE_OVERLOADS(fmin)
#undef hypotf
_AVR_GENERATE_OVERLOADS(hypot)
#undef ilogbf
_AVR_GENERATE_OVERLOADS(ilogb)
#undef lgammaf
_AVR_GENERATE_OVERLOADS(lgamma)
#undef llrintf
_AVR_GENERATE_OVERLOADS(llrint)
#undef llroundf
_AVR_GENERATE_OVERLOADS(llround)
#undef log1pf
_AVR_GENERATE_OVERLOADS(log1p)
#undef log2f
_AVR_GENERATE_OVERLOADS(log2)
#undef logbf
_AVR_GENERATE_OVERLOADS(logb)
#undef lrintf
_AVR_GENERATE_OVERLOADS(lrint)
#undef lroundf
_AVR_GENERATE_OVERLOADS(lround)
#undef nearbyintf
_AVR_GENERATE_OVERLOADS(nearbyint)
#undef nextafterf
_AVR_GENERATE_OVERLOADS(nextafter)
#undef nexttowardf
_AVR_GENERATE_OVERLOADS(nexttoward)
#undef remainderf
_AVR_GENERATE_OVERLOADS(remainder)
#undef remquof
_AVR_GENERATE_OVERLOADS(remquo)
#undef roundf
_AVR_GENERATE_OVERLOADS(round)
#undef truncf
_AVR_GENERATE_OVERLOADS(trunc)
#endif
#endif // __AVR__

#endif
