#ifndef _MATHH_PREFIX
#define _MATHH_PREFIX

#ifdef __AVR__

// List generated by running this on the errors when trying to build:
// grep "has not been declared" errors | sed -r "s/.*::([^']+)[lf].*/\1/" | uniq > calls
// cat calls | sed -r 's/(.*)/#define \1l \1/'

#define acosl acos
#define asinl asin
#define atanl atan
#define atan2l atan2
#define ceill ceil
#define cosl cos
#define coshl cosh
#define expl exp
#define fabsl fabs
#define floorl floor
#define fmodl fmod
#define frexpl frexp
#define ldexpl ldexp
#define logl log
#define log10l log10
#define modfl modf
#define powl pow
#define sinl sin
#define sinhl sinh
#define sqrtl sqrt
#define tanl tan
#define cbrtl cbrt
#define copysignl copysign
#define fdiml fdim
#define fmal fma
#define fmaxl fmax
#define fminl fmin
#define hypotl hypot
#define lrintl lrint
#define lroundl lround
#define roundl round
#define truncl trunc

#endif // __AVR__

#endif
